#!/usr/bin/env -S npx tsx
/**
 * Opens (or updates) a GitHub issue summarizing a failed SEO/Lighthouse run.
 *
 * Required env (provided by GitHub Actions by default):
 *   GITHUB_TOKEN        Token with `issues:write` on the repo
 *   GITHUB_REPOSITORY   "owner/repo"
 *   GITHUB_RUN_ID, GITHUB_RUN_URL, GITHUB_SHA, GITHUB_REF_NAME
 *
 * Reads ./reports/{post-publish-summary,lighthouse-summary}.json and
 * de-duplicates by title (one open issue per branch).
 */
import { appendFileSync, existsSync, readFileSync } from "fs";
import { resolve, join } from "path";
const setOutput = (k: string, v: string | number) => {
  if (process.env.GITHUB_OUTPUT) appendFileSync(process.env.GITHUB_OUTPUT, `${k}=${v}\n`);
};

const REPORT_DIR = resolve(process.env.REPORT_DIR || "./reports");
const token = process.env.GITHUB_TOKEN;
const repo = process.env.GITHUB_REPOSITORY;
if (!token || !repo) {
  console.error("Missing GITHUB_TOKEN or GITHUB_REPOSITORY — skipping issue creation.");
  process.exit(0);
}

const branch = process.env.GITHUB_REF_NAME || "unknown";
const sha = (process.env.GITHUB_SHA || "").slice(0, 7);
const runUrl = process.env.GITHUB_RUN_URL || `https://github.com/${repo}/actions/runs/${process.env.GITHUB_RUN_ID}`;

const read = (f: string) => (existsSync(join(REPORT_DIR, f)) ? JSON.parse(readFileSync(join(REPORT_DIR, f), "utf8")) : null);
const verify = read("post-publish-summary.json");
const lh = read("lighthouse-summary.json");

const failedSteps = (verify?.steps ?? []).filter((s: any) => !s.ok);
const lhFailures = (lh?.results ?? []).flatMap((r: any) => r.failures.map((f: string) => `${r.url}: ${f}`));

if (failedSteps.length === 0 && lhFailures.length === 0) {
  console.log("No failures detected, skipping issue.");
  process.exit(0);
}

const title = `[SEO] Regression on ${branch} (${sha || "unknown"})`;
const body = [
  `**Branch:** \`${branch}\``,
  `**Commit:** \`${sha}\``,
  `**Run:** ${runUrl}`,
  ``,
  `## Post-publish verification`,
  failedSteps.length
    ? failedSteps.map((s: any) => `- ❌ **${s.name}** — ${s.detail}`).join("\n")
    : "_All checks passed._",
  ``,
  `## Lighthouse`,
  lhFailures.length ? lhFailures.map((f: string) => `- ❌ ${f}`).join("\n") : "_All thresholds met._",
  ``,
  `## FAQPage JSON-LD`,
  verify?.faq
    ? `- status: \`${verify.faq.found ? (verify.faq.warnings?.length ? "warning" : "valid") : "missing"}\`\n- questions: ${verify.faq.questions}\n- warnings: ${verify.faq.warnings?.length || 0}`
    : "_No data._",
  ``,
  `## Artifacts`,
  `Reports + full-page screenshots are attached to the workflow run as the \`seo-report\` artifact.`,
  ``,
  `_Auto-generated by \`scripts/open-github-issue.ts\`. This issue is updated on each failing run for the same branch._`,
].join("\n");

const headers = {
  Authorization: `Bearer ${token}`,
  Accept: "application/vnd.github+json",
  "X-GitHub-Api-Version": "2022-11-28",
  "Content-Type": "application/json",
  "User-Agent": "lovable-seo-bot",
};

// Find existing open issue with the same title.
const searchRes = await fetch(
  `https://api.github.com/search/issues?q=${encodeURIComponent(`repo:${repo} is:issue is:open in:title "${title}"`)}`,
  { headers },
);
const searchBody = await searchRes.json() as any;
const existing = searchBody?.items?.find((i: any) => i.title === title);

if (existing) {
  const r = await fetch(`https://api.github.com/repos/${repo}/issues/${existing.number}/comments`, {
    method: "POST", headers, body: JSON.stringify({ body: `New failing run: ${runUrl}\n\n${body}` }),
  });
  console.log(`✓ Updated existing issue #${existing.number} (HTTP ${r.status})`);
  setOutput("issue_number", existing.number);
} else {
  const r = await fetch(`https://api.github.com/repos/${repo}/issues`, {
    method: "POST", headers, body: JSON.stringify({ title, body, labels: ["seo", "automated"] }),
  });
  const j = await r.json() as any;
  console.log(`✓ Opened issue #${j.number} (HTTP ${r.status}): ${j.html_url}`);
  if (j.number) setOutput("issue_number", j.number);
}
